version: "3.9"

services:
  backend:
    build: ./backend
    env_file: .env
    volumes:
      - ./uploads:/app/uploads
    expose:
      - "8001"
    restart: always

  frontend:
    build: ./frontend
    volumes:
      - frontend_dist:/app
    entrypoint: ["/bin/true"]
    restart: "no"

  nginx:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  frontend_dist:
