name: Test dsc_api

on:
  push:
    paths:
      - 'backend/dsc_api/**'
  pull_request:
    paths:
      - 'backend/dsc_api/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/dsc_api

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django python-dotenv

    - name: Create .env file
      run: |
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > .env

    - name: Run tests
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        pytest
